#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  2 08:18:28 2017

@author: benjamin-wuthe
"""


from bs4 import BeautifulSoup
import requests

lookingFor =  "Schule"
plz = "10245"

url = "https://www.gelbeseiten.de/" + lookingFor + "/berlin,," + plz 

r = requests.get(url)

html = r.text
soup = BeautifulSoup(html)

result = soup.find_all("span",{"class:", "gs_titel_anzahlTreffer"})

print(result[0].text)
