#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  2 08:18:28 2017

@author: benjamin-wuthe
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

readerPLZ = pd.read_excel("Berliner PLZ.xlsx")

df = pd.DataFrame(readerPLZ[:])

for index, row in df.iterrows():
   print row['Berliner PLZ']
    
lookingFor = ['Supermarkt','Arzt']


Anzahl=[]
PlzList=[]
SuchObjekt=[]

for element in lookingFor:
    
    #print element + ' an Index ' + str(lookingFor.index(element) +"\n\n")
#Die gesuchten Objekte durchgehen   
    for index, row in df.iterrows():
#Die PLZ durchgehen

        try: 
            url = "https://www.gelbeseiten.de/" + element + "/berlin,," + str(row['Berliner PLZ'])

            r = requests.get(url)

            html = r.text
    
            soup = BeautifulSoup(html)
            
            result = soup.find_all("span",{"class:", "gs_titel_anzahlTreffer"})
            
            print(element + "  in  " + str(row['Berliner PLZ']))
            
            if result[0]<=0:
                print "Gibts nicht"
            else:
                print ( result[0].text)

            Anzahl.append(result[0].text)
            PlzList.append(row['Berliner PLZ'])
            SuchObjekt.append(element) 
            
        except:
            pass
            
print "------------------------------------------------------------------"

df = pd.DataFrame({'PLZ' : PlzList, 'Anzahl' : Anzahl, 'SuchObjekt': SuchObjekt})

PlzList.append(df)

#df.({'Anhang':PlzList})

print df
writer=pd.ExcelWriter('PLZ_2.xlsx')
df.to_excel(writer,'PLZ_KPI')
writer.save()
