#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 30 18:20:47 2017

@author: benjamin-wuthe
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd


url='http://www.plz-postleitzahl.de/land.berlin/berlin/index.html'
r=requests.get(url)

soup = BeautifulSoup(r.text)
soup.prettify()

#links=soup.find_all("a")

#for link in links:
#    print("<a href='%s'>%s</a>" %(link.get("href"), link.text))
    
dataset=soup.find_all("a")
#areas=["Postleitzahlen"]
#myarr= areas[0]
myarr=""
for data in dataset:
    try:
        if long(data.text)>10000:
            myarr = data.text+ ", " +myarr 
            #ar.add(data.text)
            #print(data.text)
    except:
        pass

myarr= myarr.split(", ")

print(myarr)
df = pd.DataFrame(myarr, columns=["Berliner_PLZ"])


df.to_csv('Plz.csv', index=False)
